import { NextResponse } from "next/server";
import crypto from "crypto";

import { db } from "@/db";
import {
  bookings,
  customers,
} from "@/db/schema";

import { and, eq } from "drizzle-orm";

const COOKIE_NAME =
  "wsh_customer_session";

const COOKIE_MAX_AGE =
  60 * 60 * 24 * 30;

function hashValue(value: string) {
  return crypto
    .createHash("sha256")
    .update(value)
    .digest("hex");
}

/**
 * Creates a deterministic device/session secret from:
 *
 * booking id + access code
 *
 * IMPORTANT:
 * This is only the temporary/simple pairing implementation.
 * The final production version should use a short-lived one-time
 * pairing token generated by the staff device.
 */
function createSessionToken(
  bookingId: number,
  accessCode: string,
) {
  return crypto
    .createHmac(
      "sha256",
      process.env.SESSION_SECRET ||
        "workspace-hub-dev-secret",
    )
    .update(
      `${bookingId}:${accessCode}`,
    )
    .digest("hex");
}

export async function POST(
  req: Request,
) {
  try {
    // -------------------------------------------------------------------------
    // BODY
    // -------------------------------------------------------------------------

    const body =
      (await req
        .json()
        .catch(() => null)) as {
        accessCode?: string;
      } | null;

    const accessCode =
      typeof body?.accessCode ===
      "string"
        ? body.accessCode.trim()
        : "";

    // -------------------------------------------------------------------------
    // VALIDATE ACCESS CODE
    // -------------------------------------------------------------------------

    if (!/^\d{4}$/.test(accessCode)) {
      return NextResponse.json(
        {
          error:
            "Enter the 4-digit access code.",
        },
        {
          status: 400,
        },
      );
    }

    // -------------------------------------------------------------------------
    // FIND ACTIVE SESSION
    //
    // The 4-digit code identifies the customer's
    // currently active session.
    // -------------------------------------------------------------------------

    const [booking] =
      await db
        .select({
          id: bookings.id,

          accessCode:
            bookings.accessCode,

          accessTokenHash:
            bookings.accessTokenHash,

          customerName:
            customers.name,
        })
        .from(bookings)
        .innerJoin(
          customers,
          eq(
            customers.id,
            bookings.customerId,
          ),
        )
        .where(
          and(
            eq(
              bookings.accessCode,
              accessCode,
            ),
            eq(
              bookings.status,
              "active",
            ),
          ),
        )
        .limit(1);

    if (!booking) {
      return NextResponse.json(
        {
          error:
            "Invalid or expired access code.",
        },
        {
          status: 401,
        },
      );
    }

    // -------------------------------------------------------------------------
    // CREATE SESSION COOKIE
    //
    // We use a server-generated value derived from the active
    // booking and the access code.
    // -------------------------------------------------------------------------

    const sessionToken =
      createSessionToken(
        booking.id,
        accessCode,
      );

    const sessionHash =
      hashValue(sessionToken);

    // -------------------------------------------------------------------------
    // STORE THE COOKIE TOKEN HASH IN THE EXISTING
    // ACCESS TOKEN COLUMN.
    //
    // IMPORTANT:
    // This intentionally replaces the previous token hash for the
    // active booking so future public requests can identify the session.
    // -------------------------------------------------------------------------

    await db
      .update(bookings)
      .set({
        accessTokenHash:
          sessionHash,

        accessTokenCreatedAt:
          new Date(),
      })
      .where(
        eq(
          bookings.id,
          booking.id,
        ),
      );

    // -------------------------------------------------------------------------
    // RESPONSE
    // -------------------------------------------------------------------------

    const response =
      NextResponse.json({
        ok: true,

        bookingId:
          booking.id,

        customerName:
          booking.customerName,

        message:
          "Device connected successfully.",
      });

    response.cookies.set({
      name:
        COOKIE_NAME,

      value:
        sessionToken,

      httpOnly: true,

      secure:
        process.env.NODE_ENV ===
        "production",

      sameSite: "lax",

      path: "/",

      maxAge:
        COOKIE_MAX_AGE,
    });

    return response;
  } catch (error) {
    console.error(
      "Customer session verification failed:",
      error,
    );

    return NextResponse.json(
      {
        error:
          "Could not connect this phone.",
      },
      {
        status: 500,
      },
    );
  }
}